name: covid19
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Package adds bloc features to dart with minimal boilerplate.
  bloc: ^3.0.0
  # Package to consume the bloc features provided by 'bloc'
  flutter_bloc: ^3.2.0
  # Package to make HTTP requests
  http: ^0.12.0+4
  # The coveted provider
  provider: ^4.0.4
  # Package to pain charts on Screen
  fl_chart: ^0.8.7
  # Provides application directories
  path_provider: ^1.6.5
  # Package for managing application caching (Files - Used for Images currently)
  flutter_cache_manager: ^1.1.3
  # Package to consume the chaced Images and pre-fetch them
  cached_network_image: ^2.0.0
  # Package to launch OS specific URLs
  url_launcher: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.14.2
  test_api: ^0.2.13
  lint: ^1.0.0

dependency_overrides:
  test_api: ^0.2.13

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/

  fonts:
    # Default font to be used all over the application
    - family: QuickSand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
    - family: Covid19Icons
      fonts:
        - asset: assets/fonts/Covid19Icons.ttf
